// <auto-generated />
namespace CCS2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Messages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Messages));
        
        string IMigrationMetadata.Id
        {
            get { return "201310251529498_Messages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
