// <auto-generated />
namespace CCS2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class replyMessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(replyMessage));
        
        string IMigrationMetadata.Id
        {
            get { return "201310251543124_replyMessage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
