// <auto-generated />
namespace CCS2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RequestKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequestKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201310241959492_RequestKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
