// <auto-generated />
namespace CCS2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class bills : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bills));
        
        string IMigrationMetadata.Id
        {
            get { return "201312022118095_bills"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
