// <auto-generated />
namespace CCS2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class billdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(billdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201312022155178_bill-date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
