// <auto-generated />
namespace CCS2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class messageSendTo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(messageSendTo));
        
        string IMigrationMetadata.Id
        {
            get { return "201311130046208_messageSendTo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
