// <auto-generated />
namespace CCS2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Idelete_Message : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Idelete_Message));
        
        string IMigrationMetadata.Id
        {
            get { return "201311200018544_Idelete_Message"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
